vich_uploader:
    db_driver: orm

    mappings:
        medias:
            uri_prefix: /medias/
            upload_destination: '%kernel.project_dir%/public/media/'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }
